name: Publish

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd chapter_1/01_control_dependencies/zp3_v1
        poetry publish --build -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
        cd chapter_1/01_control_dependencies/zp3_v2
        poetry publish --build -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}